### ISSUE TITLE
Multiple Issues With Armor Trims & Lang

### ISSUE THREAD

**Issue by Jusey1** [AbraXator/MoreSnifferFlowers#2]
[Fixed.zip](https://github.com/AbraXator/MoreSnifferFlowers/files/12340606/Fixed.zip)

Since this part of the mod is all assets, I fixed it myself and am just submitting the fixes here in a zip file. This greyscales the Aroma Armor Trim so that it works with any material, fixed the Atlas to properly register the Aroma Armor Trim for every material, fixed the lang file for the Aroma Armor Trim & missing Amber Material translation line.

Side note: The Banner Pattern is stackable (they are suppose to be unstackable). Also, doesn't seem like that the Amber block is properly tagged so it has a recommended tool but I assume that's intentional.

**Comment by AbraXator** [comment]
Thank you for finding and fixing these issues, they'll be fixed in the newest update!

**Comment by Jusey1** [comment]
Danke for applying most of my fixes though did you forgot about the greyscale fix for the armor trim?

**Comment by Jusey1** [comment]
Ye'h, no worries. The only bug left should be the one with the sniffer digging up three seeds at a time but it looks like you are working on fixing that base on the recent edits of the source code.
